# Generated by Django 4.0.3 on 2022-03-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_article_author_message_article_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='base.message'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
