# Generated by Django 4.0.3 on 2022-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_article_messages_alter_article_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topics',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='article',
            name='messages',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
